#!/bash

set -euo pipefail

source "$BPAN_ROOT/lib/bpan.bash" --

bpan:source bashplus +cmd +sys
bpan:source test-tap --

export BPAN_TEST_RUNNING=1

FILE=$0
NAME=$(basename "$FILE")
NAME=${NAME%.t}
ROOT=$(cd "$(dirname "$FILE")"/.. && pwd -P)
TEST=$ROOT/test

if [[ $* == *chdir* ]]; then
  cd "$TEST/$NAME"
fi

if [[ $* == *slow* ]]; then
  if [[ -z ${SLOW-} ]]; then
    pass "Use SLOW=1 to run slow tests"
    done-testing
    exit 0
  fi
fi
