#!/bash

set -euo pipefail

source "$BPAN_ROOT/lib/bpan.bash" --

bpan:source bashplus +cmd +sys
bpan:source test-tap --

export BPAN_TEST_RUNNING=1

# Add any custom initialization to a test/init-local file.
if [[ -f test/init-local ]]; then
  source test/init-local
fi
