#!/bash

set -euo pipefail

source "$BPAN_ROOT/lib/bpan.bash" --

bpan:source bashplus +cmd +sys
bpan:source test-tap --

export BPAN_TEST_RUNNING=1

FILE=$0
NAME=$(basename "$FILE")
NAME=${NAME%.t}
ROOT=$(cd "$(dirname "$FILE")"/.. && pwd -P)
[[ -f $ROOT/License ]] ||
  ROOT=$(cd "$(dirname "$FILE")"/../.. && pwd -P)
[[ -f $ROOT/License ]] ||
  die "Can't find ROOT"
TEST=$ROOT/test

if [[ $* == *slow* ]]; then
  if [[ -z ${slow-} ]]; then
    pass "Use slow=1 to run slow tests"
    done-testing
    exit 0
  fi
fi

if [[ $* == *chdir* ]]; then
  cd "$TEST/$NAME"
fi
