R-VERSION ?= 4.6.0
# https://www.r-project.org
# https://github.com/r-hub/R

ifndef R-LOADED
R-LOADED := true
$(if $(MAKES),,$(error Please 'include init.mk' first))
$(eval $(call include-local))

OA-linux-arm64 := glibc-aarch64
OA-linux-int64 := glibc-x86_64
OA-macos-arm64 := arm64
OA-macos-int64 := x86_64

R-DIR := r-$(R-VERSION)
R-LOCAL := $(LOCAL-ROOT)/$(R-DIR)

ifdef IS-WINDOWS
# The r-hub project has no Windows builds; use the official CRAN
# InnoSetup installer (every release is kept under old/):
R-ARCHIVE := R-$(R-VERSION)-win.exe
R-DOWN := https://cran.r-project.org/bin/windows/base/old
R-DOWN := $(R-DOWN)/$(R-VERSION)/$(R-ARCHIVE)
else
ifdef IS-LINUX
R-ARCHIVE := r-$(R-VERSION)-$(OA-$(OS-ARCH)).tar.gz
else
R-ARCHIVE := R-$(R-VERSION)-$(OA-$(OS-ARCH)).pkg
endif
R-DOWN := https://github.com/r-hub/R/releases/download
R-DOWN := $(R-DOWN)/v$(R-VERSION)/$(R-ARCHIVE)
endif

ifdef IS-MACOS
R-FRAMEWORK := $(R-LOCAL)/Library/Frameworks/R.framework
R-BIN := $(LOCAL-BIN)
else
R-BIN := $(R-LOCAL)/bin
override PATH := $(R-BIN):$(PATH)
export PATH
endif

ifdef IS-WINDOWS
R := $(R-BIN)/R.exe
else
R := $(R-BIN)/R
endif

SHELL-DEPS += $(R)


R-ORIG-PREFIX := /opt/R/$(R-VERSION)-glibc

# The build prefix is compiled into base.rdb (notably the tools/which
# path used by Sys.which) and cannot be sed-patched there. Rebind
# Sys.which at startup via Rprofile.site. Note: R --vanilla skips the
# site profile; use --no-save --no-restore --no-init-file instead.
define R_PROFILE_SITE_CODE
# Generated by makes r.mk for the relocated R installation.
local({
  wp <- file.path(R.home(), "tools", "which")
  if (!file.exists(wp)) wp <- "which"
  sw <- function(names) {
    res <- character(length(names))
    names(res) <- names
    for (i in seq_along(names)) {
      test <- tryCatch(
        suppressWarnings(system(
          paste(shQuote(wp), shQuote(names[i])),
          intern = TRUE, ignore.stderr = TRUE)),
        error = function(e) character())
      res[i] <- if (length(test)) test[1] else ""
    }
    res
  }
  base::unlockBinding("Sys.which", baseenv())
  assign("Sys.which", sw, envir = baseenv())
  base::lockBinding("Sys.which", baseenv())
})
endef
export R_PROFILE_SITE_CODE

$(R): $(LOCAL-CACHE)/$(R-ARCHIVE)
ifdef IS-WINDOWS
	chmod +x $<
# MSYS bash rewrites /FLAG arguments into Windows paths when calling
# native programs; disable that conversion for the installer flags:
	MSYS2_ARG_CONV_EXCL='*' MSYS_NO_PATHCONV=1 \
	  $< /SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART \
	  "/DIR=$$(cygpath -w $(R-LOCAL))"
else
ifdef IS-LINUX
	mkdir -p $(R-LOCAL)
	tar -C $(R-LOCAL) --strip-components=3 -xzf $<
	sed -i 's|$(R-ORIG-PREFIX)|$(R-LOCAL)|g' \
	  $(R-LOCAL)/bin/R \
	  $(R-LOCAL)/bin/Rscript \
	  $(R-LOCAL)/lib/R/bin/R \
	  $(R-LOCAL)/lib/R/bin/Rscript \
	  $(R-LOCAL)/lib/R/etc/ldpaths \
	  $(R-LOCAL)/lib/R/etc/Makeconf \
	  $(R-LOCAL)/lib/R/etc/Renviron
	printf '%s\n' "$$R_PROFILE_SITE_CODE" \
	  > $(R-LOCAL)/lib/R/etc/Rprofile.site
	[[ -e $@ ]]
else
	rm -rf $(LOCAL-CACHE)/R-pkg-tmp
	pkgutil --expand $< $(LOCAL-CACHE)/R-pkg-tmp
	mkdir -p $(R-LOCAL)
	@for pkg in $(LOCAL-CACHE)/R-pkg-tmp/*.pkg; do \
	  [ -f "$$pkg/Payload" ] || continue; \
	  gunzip -c "$$pkg/Payload" | (cd $(R-LOCAL) && cpio -id 2>/dev/null); \
	done
	rm -rf $(LOCAL-CACHE)/R-pkg-tmp
	ln -sf $(R-FRAMEWORK)/Versions/Current/Resources/bin/R $@
	ln -sf $(R-FRAMEWORK)/Versions/Current/Resources/bin/Rscript \
	  $(LOCAL-BIN)/Rscript
	[[ -e $@ ]]
endif
endif
	touch $@
	@echo

$(LOCAL-CACHE)/$(R-ARCHIVE):
	@echo "* Installing 'R' locally"
	curl+ $(R-DOWN) > $@

endif
