#!/usr/bin/env bash

set -euo pipefail

die() { echo "$@" >&2; exit 1; }

main() {
  [[ $# -eq 1 && $1 == https://* ]] ||
    die "curl+ takes one arg which must be a url"

  local url=$1
  local name=${url#https://}
  name=${name//\//__}

  local target
  target=$(mktemp)
  # shellcheck disable=SC2064  # expand $target now: it's local to main()
  trap "rm -f '$target'" EXIT

  local makes_cache=${BASH_SOURCE[0]%/*}/makes-cache

  MAKES_CACHE_NAME=$name \
  MAKES_CACHE_DEPS=_ \
  "$makes_cache" "$target" \
    curl -fsSL --retry 5 --retry-delay 3 --retry-all-errors -o "$target" "$url"

  cat "$target"
}

main "$@"
