#!/usr/bin/env bash

set -o pipefail

mode=$1; shift
logfile=$1; shift
MAKE=$1; shift
MAKEFILE=$1; shift

overrides=()
targets=()
sep=false
for arg in "$@"; do
    if [[ $arg == '--' ]]; then
        sep=true
        continue
    fi
    if $sep; then
        targets+=("$arg")
    else
        overrides+=("$arg")
    fi
done

cmd=("$MAKE" -f "$MAKEFILE" "${overrides[@]}" "${targets[@]}")

case $mode in
    tee)
        "${cmd[@]}" 2>&1 | tee "$logfile"
        ;;
    script)
        if [[ $OSTYPE == darwin* ]]; then
            exec script -qF "$logfile" "${cmd[@]}"
        else
            exec script -qfc "${cmd[*]}" "$logfile"
        fi
        ;;
esac
