#!/usr/bin/env bash

set -euo pipefail

main() (
  target=$1; shift

  if [[ ${MAKES_CACHE_DIR-} ]]; then
    [[ -d $MAKES_CACHE_DIR ]] ||
      die "MAKES_CACHE_DIR=$MAKES_CACHE_DIR is not a directory"
    cache_dir=$MAKES_CACHE_DIR
  elif [[ -d ~/.cache/makes ]]; then
    cache_dir=~/.cache/makes
  fi

  # No caching if no cache dir available
  [[ ${cache_dir-} ]] || {
    exec "$@"
  }

  deps=${MAKES_CACHE_DEPS:-$*}
  if [[ $deps == _ ]]; then
    cache_path=$cache_dir/${MAKES_CACHE_NAME:?}
  else
    hash=$(sha1 <<<"$deps")
    cache_path=$cache_dir/${MAKES_CACHE_NAME:?}-$hash
  fi

  # Cache hit - restore and exit
  if [[ -e $cache_path ]]; then
    rm -rf "$target"
    cp -a "$cache_path" "$target"
    touch "$target"
    echo "Restored from cache: $cache_path" >&2
    exit 0
  fi

  # Cache miss - run command
  "$@"

  # If target exists, cache it
  if [[ -e $target ]]; then
    cp -a "$target" "$cache_path"
    touch "$target"
    echo "Cached: $cache_path" >&2
  fi
)

sha1() (
  if command -v sha1sum &>/dev/null; then
    sha1sum | cut -f1 -d' '
  else
    shasum -a 1 | cut -f1 -d' '
  fi
)

die() { printf '%s\n' "$@" >&2; exit 1; }

main "$@"
